services:
  web:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: php:8.4-fpm
    volumes:
      - ./src:/var/www/html
  db:
    image: postgres
    ports:
      - "220:5432"
    environment:
      POSTGRES_PASSWORD: example
